const CarouselData = [
    {
       'id':1,
       'image':'/images/recentActivities/0_DSC_0041.jpg',
       'leftTitle':'ROBOWAR',
       'rightTitle':'TCF24'
    },
    {
        'id':2,
        'image':'/images/recentActivities/0_DSC_0069.jpg',
        'leftTitle':'ROBOWAR',
        'rightTitle':'TCF24'
     },
     {
        'id':3,
        'image':'/images/recentActivities/0_DSC06737.jpg',
        'leftTitle':'ROBOWAR',
        'rightTitle':'TCF24'
     },
     {
        'id':4,
        'image':'/images/recentActivities/1_DSC_0003.jpg',
        'leftTitle':'LASER BOT',
        'rightTitle':'TCF24'
     },
     {
        'id':5,
        'image':'/images/recentActivities/1_DSC_0057_1.jpg',
        'leftTitle':'ROBOWAR',
        'rightTitle':'TCF24'
     },
     {
        'id':6,
        'image':'/images/recentActivities/1_DSC06797(1).jpg',
        'leftTitle':'ROBOWAR',
        'rightTitle':'TCF24'
     },
     {
        'id':7,
        'image':'/images/recentActivities/2_DSC06791.jpg',
        'leftTitle':'ROBOWAR',
        'rightTitle':'TCF24'
     },
     {
        'id':8,
        'image':'/images/recentActivities/4_DSC06787.jpg',
        'leftTitle':'ROBOWAR',
        'rightTitle':'TCF24'
     },
     {
        'id':9,
        'image':'/images/recentActivities/8_DSC06740.jpg',
        'leftTitle':'LASER BOT',
        'rightTitle':'TCF24'
     },
     {
        'id':10,
        'image':'/images/recentActivities/9_DSC_0017_1.jpg',
        'leftTitle':'EVENT',
        'rightTitle':'TCF24'
     }
]

export default CarouselData